### ISSUE TITLE
Consider not using a min file

### ISSUE THREAD

**Issue by ruyadorno** [marloscarmo/data-metrics#4]
The specs for `bower.json` defines that the [main file should not be minified](https://github.com/bower/bower.json-spec#main).

A common pattern is to provide:
- a concatenated-only file on the dist folder and declare it on bower.json main property 
- an optional minified file on the dist folder that is not listed on the bower.json file

**Comment by ruyadorno** [comment]
I haven't really seen before that all the javascript is a one-file, we can fix this one by just pointing the _main_ bower.json property to `src/data-metrics.js`

**Comment by erickbelfy** [comment]
Following the bower standards, i changed the main property to right path, `src/data-metrics.js`. Thanks!
